<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints" Version="6.0.0"/>
        <PackageReference Include="FastEndpoints.Security" Version="6.0.0"/>
        <PackageReference Include="FastEndpoints.Swagger" Version="6.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.4"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Sampld.Application\Sampld.Application.csproj"/>
        <ProjectReference Include="..\Sampld.Domain\Sampld.Domain.csproj"/>
        <ProjectReference Include="..\Sampld.Infrastructure\Sampld.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
